[twitter]

api_key = lAxasaI6Bhk4U9xPfzf5jJTIi
api_key_secret = fmbakoQvWtIlcq6alATOoe1GxlseAN8eY6Cm6CKU0BwINrGygQ



CONSUMER_KEY = TTcIc5TjBKwIJsmhE2wMsqy4V
CONSUMER_SECRET = 4NeoVLvqYfgrNVmR3Fh0nAmxg7RMHj3xNuOqXPdPueHYlf8KUF

#new
ACCESS_TOKEN = 1569207846893670400-SQEN0eP8DLqXoOfkkw5bsCm7psnIZB
ACCESS_TOKEN_SECRET = JBTAELm5Lk6XtmzioTFor3SNpJvgMVD40GuUoTL4elpUY

BEARER_TOKEN = AAAAAAAAAAAAAAAAAAAAANDYiAEAAAAAw3nrBF27qeG53dirmY6ioC6q3IA%%3DBZQNczzE3vuB1SZTICzPnfbR3OpZSgDntu1Q7dBFRw4PgOYOkj

client_secret = lmYZmrLh0rJRN_IlYD_R4r86_rZ662od0TtIdYtc3QCavd4mhQ